version: "3.9"

services:
  triviabot-backend:
    build: ./backend-server
    container_name: triviabot-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    expose:
      - "3002"
    networks:
      - trivia
    dns:
      - 8.8.8.8
      - 1.1.1.1

  triviabot-dashboard:
    build: ./dashboard-app
    container_name: triviabot-dashboard
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=https://api.trivia.willflexbot.uk
    expose:
      - "80"
    labels:
      - "VIRTUAL_HOST=trivia.willflexbot.uk"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=trivia.willflexbot.uk"
      - "LETSENCRYPT_EMAIL=your-email@example.com"
    networks:
      - trivia
      - nginx-proxy
    dns:
      - 8.8.8.8
      - 1.1.1.1

  triviabot-bot:
    build: ./bot-app
    container_name: triviabot-bot
    restart: unless-stopped
    depends_on:
      - triviabot-backend
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BACKEND_URL=http://triviabot-backend:3002
      - TRIVIA_CHANNEL_ID=${TRIVIA_CHANNEL_ID}
    networks:
      - trivia
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  trivia:
    external: false
  nginx-proxy:
    external: true