version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: triviabot-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  backend:
    build: ./backend-server
    container_name: triviabot-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3002"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}

  dashboard:
    build: ./dashboard-app
    container_name: triviabot-dashboard
    restart: unless-stopped
    ports:
      - "5175:5173"
    volumes:
      - ./dashboard-app:/app

  bot:
    build: ./bot-app
    container_name: triviabot-bot
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      BACKEND_URL: http://triviabot-backend:3002
      TRIVIA_CHANNEL_ID: ${TRIVIA_CHANNEL_ID}