version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: triviabot-traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend-server/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-net

  triviabot-backend:
    build:
      context: .
      dockerfile: backend-server/Dockerfile
    container_name: triviabot-backend
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    expose:
      - "3002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.triviabot-backend.rule=Host(`api.trivia.willflexbot.uk`)"
      - "traefik.http.routers.triviabot-backend.entrypoints=web"
      - "traefik.http.services.triviabot-backend.loadbalancer.server.port=3002"
    networks:
      - trivia
      - traefik-net

  triviabot-dashboard:
    build: ./dashboard-app
    container_name: triviabot-dashboard
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=https://api.trivia.willflexbot.uk
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.triviabot-dashboard.rule=Host(`trivia.willflexbot.uk`)"
      - "traefik.http.routers.triviabot-dashboard.entrypoints=web"
      - "traefik.http.services.triviabot-dashboard.loadbalancer.server.port=80"
    networks:
      - trivia
      - traefik-net

  triviabot-bot:
    build: ./bot-app
    container_name: triviabot-bot
    restart: unless-stopped
    depends_on:
      - triviabot-backend
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BACKEND_URL=http://triviabot-backend:3002
      - TRIVIA_CHANNEL_ID=${TRIVIA_CHANNEL_ID}
    networks:
      - trivia

networks:
  trivia:
    external: false
  traefik-net:
    external: true