version: "3.9"

services:
  # Backend API
  triviabot-backend:
    build: ./backend-server
    container_name: triviabot-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    expose:
      - "3002"
    networks:
      - trivia
    labels:
      - "traefik.http.routers.triviabot-backend.rule=Host(`api.trivia.willflexbot.uk`)"
      - "traefik.http.routers.triviabot-backend.entrypoints=websecure"
      - "traefik.http.services.triviabot-backend.loadbalancer.server.port=3002"

  # Dashboard Frontend
  triviabot-dashboard:
    build: ./dashboard-app
    container_name: triviabot-dashboard
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=https://api.trivia.willflexbot.uk
    expose:
      - "5173"
    networks:
      - trivia
    labels:
      - "traefik.http.routers.triviabot-frontend.rule=Host(`trivia.willflexbot.uk`)"
      - "traefik.http.routers.triviabot-frontend.entrypoints=websecure"
      - "traefik.http.services.triviabot-frontend.loadbalancer.server.port=5173"

  # Discord Bot
  triviabot-bot:
    build: ./bot-app
    container_name: triviabot-bot
    restart: unless-stopped
    depends_on:
      - triviabot-backend
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BACKEND_URL=http://triviabot-backend:3002
      - TRIVIA_CHANNEL_ID=${TRIVIA_CHANNEL_ID}
    networks:
      - trivia

networks:
  trivia:
    external: false