version: "3.9"

services:
  triviabot-backend:
    build:
      context: .
      dockerfile: backend-server/Dockerfile
    container_name: triviabot-backend
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    ports:
      - "3002:3002"

  triviabot-dashboard:
    build: ./dashboard-app
    container_name: triviabot-dashboard
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://localhost:3002
    ports:
      - "80:80"

  triviabot-bot:
    build: ./bot-app
    container_name: triviabot-bot
    restart: unless-stopped
    depends_on:
      - triviabot-backend
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BACKEND_URL=http://triviabot-backend:3002
      - TRIVIA_CHANNEL_ID=${TRIVIA_CHANNEL_ID}